export default {
  // Module Navigation
  module: {
    index: 'Home',
    toolbox: 'AI Toolbox',
    tool: 'AI Toolbox',
    agent: 'Agent',
    chat: 'Chat',
    app: 'App',
    find: 'Discover',
    library: 'Knowledge Base',
    crop_space: 'Enterprise Space',
    prompt: 'Prompt'
  },

  // Browser Related
  browser: {
    newTab: 'New Tab',
    search_placeholder: 'Search in Baidu AI, or enter a URL',
    knowledge_clean: 'Knowledge Cleaning',
    load_error: 'Loading Failed',
    reload: 'Reload',
    not_logged_in: 'Not Logged In',
    login: 'Login Now',
    window_position: 'Window Position',
    leftWindow: 'Left Small Window',
    centerWindow: 'Center Large Window',
    rightWindow: 'Right Small Window',
    alwaysOnTop: 'Always On Top'
  },

  // Cleaning Features
  clean: {
    content: 'Content Extraction',
    knowledge: 'Knowledge Organization',
    summarize: 'Knowledge Extraction'
  },

  // Update Related
  updater: {
    newVersion: 'New version found, update now?',
    newVersionTitle: 'Update Notification',
    downloading: 'Downloading update',
    completed: 'Update completed, restart now?',
    completedTitle: 'Update Notification',
    noUpdate: 'Current version is up to date',
    currentVersion: 'Current version v{version}',
    checkUpdate: 'Check for Updates'
  },

  // Common Text
  common: {
    new_friend: 'Beginner Guide',
    help_feedback: 'Help & Feedback',
    attach: 'Attachment',
    screenshot: 'Screenshot',
    title: 'Title',
    desc: 'Description',
    tip: 'Tip',
    create_time: 'Creation Time',
    update_time: 'Update Time',
    recently_updated: 'Recently Updated',
    loading: 'Loading',
    // Load more
    load_more: 'Load More',
    load_new: 'Load New Messages',
    no_data: 'No Data',
    unknown: 'Unknown',
    usual: 'Frequently Used',

    render: 'Render',
    preview: 'Preview',
    code: 'Code',
    split: 'Split Screen',
    all: 'All',
    recently_visit: 'Recently Visited',

    confirm_delete: 'Are you sure you want to delete this item?',
    copied: 'Copied',
    image_cropper: 'Image Cropper',
    back: 'Back',
    go_admin: 'Go to Admin',
    related_prompt: 'Related Prompts',
    related_agent: 'Related Agents',
    view_more: 'View More',
    expand_more: 'Expand More',
    collapse_more: 'Collapse More',
    or: 'Or',
    later: 'Later',
    allow_to: 'Copied prompt content. Visit "{name}" site',
    ai_generated: 'Content generated by AI,仅供参考',
    back_home: 'Return to site homepage'
  },

  // Status Prompts
  status: {
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    success: 'Success',
    updated: 'Updated',
    sent: 'Sent',
    login_success: 'Logged In',
    logout_success: 'Logged Out',
    not_found_account: 'Account not found, please register first and then login',
    existing_account: 'Account already exists',
    approve_success: 'Liked',
    approve_cancel: 'Unliked',
    register_success: 'Registration successful',
    update_success: 'Update successful',
    copy_success: 'Copy successful',
    copy_error: 'Copy failed'
  },

  // Action Buttons
  action: {
    login: 'Login',
    login_directly: 'Login directly',
    logout: 'Logout',
    register: 'Register',
    user_register: 'User registration',
    forget_password: 'Forgot password?',
    update_password: 'Update password',
    search: 'Search',
    setting: 'Settings',
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
    open: 'Open',
    ok: 'OK',
    allow: 'Allow',
    and: 'and',
    copy: 'Copy',
    upload: 'Upload',
    download: 'Download',
    del: 'Delete',
    add: 'Add',
    create: 'Create',
    edit: 'Edit',
    save: 'Save',
    fixed: 'Pin',
    unfixed: 'Unpin',
    collapse: 'Collapse',
    expand: 'Expand',
    back: 'Back',
    share: 'Share',
    favorite: 'Favorite',
    unfavorite: 'Unfavorite',
    more: 'More',
    refresh: 'Refresh',
    apply: 'Apply',
    reset: 'Reset',
    submit: 'Submit',
    manage: 'Manage',
    rename: 'Rename',
    find: 'Find',
    preview: 'Preview',
    reupload: 'Re-upload',
    send: 'Send',
    stop: 'Stop',
    pay: 'Pay',
    ok_v2: 'OK',
    view_more: 'View More',
    click_upload: 'Click Upload',
    view: 'View',
    delete: 'Delete',
    select_all: 'Select All'
  },

  file: {
    file_size: 'File size must be less than {size}MB',
    file_format: 'Supported formats: {format}',
    file_empty: 'File content cannot be empty',
    file_exceed: 'File upload size cannot exceed {size}MB ({name} size exceeds)',
    file_exceed_limit: 'Upload up to {limit} files'
  },

  // Form Related
  form: {
    icon: 'Icon',
    name: 'Name',
    desc: 'Description',
    input_placeholder: 'Please enter',
    select_placeholder: 'Please select',
    icon_placeholder: 'For best display, please upload an image with a 1:1 aspect ratio',
    required: 'Required',
    optional: 'Optional',

    // Knowledge Base Public Scope
    library_view_scope: 'Knowledge Base Access Scope',
    library_view_public: 'Public Access',
    library_view_team: 'Team Space Members Access',
    library_view_member: 'Knowledge Base Members Access',

    avatar: 'Avatar',
    nickname: 'Nickname',
    select_verify: 'Please select verification method',
    email_verify: 'Email Verification',
    mobile_verify: 'Mobile Verification',
    account: 'Account',
    remark: 'Remark',
    account_alias: 'Mobile',
    password: 'Password',
    password_placeholder: 'Please enter password',
    email: 'Email',
    new_email: 'New Email',
    mobile: 'Mobile',
    new_mobile: 'New Mobile',
    verify_code: 'Verification Code',
    get_verify_code: 'Get Verification Code',
    verify_old_mobile: 'Verify your old phone number',
    reset_password: 'Reset Password',
    reset_password_method: 'Select a password reset method',
    new_password: 'New Password',
    new_password_placeholder: 'Please enter new password',
    new_password_confirm: 'Confirm New Password',
    new_password_confirm_placeholder: 'Please re-enter new password',
    mobile_format: 'Please enter a valid mobile number',
    email_format: 'Please enter a valid email',
    account_format: 'Please enter a valid mobile or email',
    verify_code_format: 'Please enter a valid verification code',
    password_length: 'Password must be between 8-20 characters',
    password_format: 'Password must contain uppercase, lowercase letters and numbers',
    password_not_match: 'The two passwords do not match',
    password_no_chinese: 'Password cannot contain Chinese characters',
    change: 'Change',
    existing_mobile: 'This mobile number has been registered. Please log in with this account.',
    existing_email: 'This email has been registered. Please log in with this account.'
  },

  // Home Related
  index: {
    agent_recommend: 'Featured Agents',
    agent_recommend_desc: 'Build your second productivity engine',
    prompt_recommend: 'Featured Prompts',
    prompt_recommend_desc: 'Use prompts well to always stay ahead',
    toolbox_recommend: 'Featured AI Tools',
    toolbox_recommend_desc: 'Select AI resources for your workflow, make AI your productivity tool',
    use_history: '{count} people have chatted',
    banner_title: '“{name} Expert” The secret weapon for efficiency',
    banner_desc: 'Select AI resources for your workflow, make AI your productivity tool',
    search_placeholder: 'Enter the AI resource you want to find',
    hot_search: 'Hot Search'
  },

  // Login Related
  login: {
    agree: 'By logging in, you agree to',
    terms_of_service: 'Terms and Conditions',
    privacy_policy: 'Privacy Policy',
    password_login: 'Password Login',
    password_login_title: 'Password Login',
    message_login: 'Message Login',
    message_login_title: 'Message Login',
    wechat_login: 'WeChat Login',
    wechat_login_title: 'WeChat Login',
    wecom_login: 'WeCom Login',
    wecom_login_title: 'WeCom Login',
    unregistered_account_desc:
      'Unregistered accounts, please register first and then automatically login',
    unregistered_account_confirm:
      'Automatically log in after verifying the unregistered mobile phone number',
    quit: 'Quit',
    login_by_wechat: 'Use WeChat Login',
    login_by_password: 'Use Password Login',
    login_by_mobile: 'Use Mobile Login',
    bind_mobile: 'Bind Mobile Number',
    other_login_way: 'Other Login Way',
    login_by_wecom: 'Use WeCom Login',
    unbind_wechat_confirm_desc:
      'After unbinding, you will not be able to log in with WeChat. Continue?',
    unbind_wechat_confirm_title: 'Unbind WeChat Account Binding',
    immediate_login: 'Immediate Login',
    wecom_login_error:
      'The enterprise wechat bound to the site is not the enterprise wechat currently logged in!\nPlease use the correct enterprise wechat to log in.'
  },

  // Registration related
  register: {
    agree: 'By registering, you agree to',
    terms_of_service: 'Terms of Service',
    privacy_policy: 'Privacy Policy',
    unregister: 'Unregister'
  },

  // Chat Related
  chat: {
    search_placholder: 'Search agents',
    collapse_side_bar: 'Collapse Sidebar',
    expand_side_bar: 'Expand Sidebar',
    history: 'Conversation History',
    new_conversation: 'New Conversation',
    edit_conversation: 'Edit Conversation Name',

    conversation_confirm_delete: 'After deletion, chat history cannot be recovered.',
    input: 'Input',
    output: 'Output',
    start_generate: 'Start Generating',
    regenerate: 'Regenerate',
    like: 'Like',
    dislike: 'Unlike',
    input_placeholder: 'Send a message',
    usage_guide: 'Usage Guide',
    completion_empty_desc:
      'Using AI large model to intelligently generate content, just input your requirements for one-click content creation',
    usage_case: 'Use Cases',
    usage_scene: 'Usage Scenarios',
    online_search: 'Online Search',
    completion_generating: 'Content generating, please wait...',
    completion_rendering: 'Content rendering...',

    // No available agents
    no_available_agent: 'No available agents',

    completion_completed: 'Deep thinking completed',
    completion_thinking: 'Deep thinking...',
    completion_scene: 'Related Scenes:',
    completion_next_action: 'Related Scenarios: Next Action',

    not_found_url: 'URL not found, please check if the agent is set correctly',
    completion_share_link: 'Conversation link copied, share now~',
    no_available_agent_desc: '很遗憾，你要访问的智能体已不存在，去看看其他有趣的智能体吧～'
  },

  // Knowledge Base Related
  library: {
    home: 'Home',
    name: 'Knowledge Base',
    create: 'Create Knowledge Base',
    all_spaces: 'All Member Space',
    space_name: 'Space Name',
    chat: 'Knowledge Base Q&A',
    file_count: '{count} files',
    upload_file: 'Upload File',
    manage: 'Manage Knowledge Base',
    search: 'Search Knowledge Base',
    all_libraries: 'All Knowledge Bases',
    empty_desc:
      'Create enterprise knowledge base, accumulate team knowledge, improve collaboration efficiency',

    create_md: 'New Knowledge',
    local_upload: 'Local Upload',
    create_folder: 'New Folder',
    tmpl_create: 'Template Creation',
    github_import: 'Import from Github',
    docs_qq_import: 'Import from Tencent Docs',
    docs_feishu_import: 'Import from DingTalk Docs',
    docs_dingtalk_import: 'Import from Feishu Docs'
  },

  agent: {
    no_data: 'No data',
    dialogue_type: 'Conversational',
    applied_type: 'Applied',
    failed_tip:
      'Please check if the authorization key is available and if the balance is sufficient.'
  },

  prompt: {
    default_sort: 'Default Sort',
    likes_sort: 'Likes Sort',
    views_sort: 'Views Sort',
    content: 'Prompt Content',
    auth_tip: 'You do not have permission to access this prompt',
    let_use_prompt: '去使用这个提示词'
  },

  toolbox: {
    // AI聚合问答
    name: 'AI Aggregation',
    title:
      'Use AI large model to intelligently generate content, just input your requirements for one-click content creation',
    input_placeholder: 'Send a message',
    max_agent_count: 'You can only select {count} agents',
    search_placeholder: 'Search website',
    direct_access: 'Direct access',
    click_access: 'Click to access',
    account_access: 'Shared account',
    account_text: 'The following are the shared account and password, for personal use only',
    account_text2: 'You can copy the shared account password to access the target site'
  },
  // Space Related
  space: {
    create: 'Create Space',
    join: 'Join Space',
    manage: 'Manage Space',
    member: 'Member Management',
    settings: 'Space Settings',
    space_usage: 'Used {used} / {total}',
    expand: 'Expand Capacity'
  },

  // Time Related
  time: {
    just_now: 'Just now',
    minutes_ago: '{count} minutes ago',
    hours_ago: '{count} hours ago',
    days_ago: '{count} days ago',
    yesterday: 'Yesterday',
    today: 'Today',
    week_last: 'Within a week',
    week_ago: 'A week ago'
  },

  profile: {
    info: 'Personal Information',
    profile: 'Profile',
    change_password: 'Change Password',
    login_password: 'Login Password',
    bind_accounts: 'Account Information',
    subscription_info: 'Subscription Information',
    order_info: 'Order Information',
    unbind_account: 'Not Bound',
    bind_mobile: 'Mobile Number',
    bind_email: 'Email',
    bind_google: 'Google',
    bind_wechat: 'WeChat',
    bind: 'Bind',
    unbind: 'Unbind',
    change: 'Change',
    logined_devices: 'Logged-in Devices',
    used_devices: 'Previously Used Devices',
    current_device: 'Current Device',
    unbind_wechat_confirm_desc:
      'After unbinding, you will not be able to log in with WeChat. Continue?',
    unbind_wechat_confirm_title: 'Unbind WeChat Account Binding',
    unbind_wechat_confirm_cancel: 'Cancel',
    unbind_wechat_confirm_ok: 'Confirm',
    renew: 'Renew',
    expire_time_desc:
      '{group_name} will expire in {day} days ({expire_time}), please renew to continue membership rights',
    expired_time_desc:
      '{group_name} has expired on {expire_time}, please renew to continue membership rights'
  },
  response_status: {
    '400': 'Request parameter error',
    '401': 'Unauthorized, please login',
    '403': 'Access denied',
    '404': 'Requested resource does not exist',
    '500': 'Server error',
    '502': 'Gateway error',
    '504': 'Gateway timeout',
    '503': 'Service unavailable'
  },
  response_code: {
    success: 'Success',
    param_error: 'Parameter error',
    database_error: 'Database error',
    network_error: 'Network error, please try again',
    system_error: 'System error',
    auth_error: 'Authentication error',
    not_found_error: 'Not found error',
    unauthorized_error: 'Authentication error',
    file_error: 'File error',
    forbidden_error: 'User is disabled, please contact the administrator',
    agent_error: 'Agent error',
    token_expired_error: 'Token expired error',
    verification_code_error: 'Verification code error'
  },
  response_message: {
    unknown_error: 'Unknown error',
    user_not_found: 'User does not exist',
    username_or_password_is_incorrect: 'Username or password is incorrect',
    username_already_exists: 'Username already exists',
    mobile_already_bind: 'The phone number has already been bound to another user',
    email_already_bind: 'The email address is already bound to another user',
    model_changed: 'The administrator has changed the model, please create a new conversation',
    wechat_already_bind: 'WeChat account has been bound to another user'
  },
  subscription: {
    free: 'Free',
    upgrade: 'Upgrade',
    version_title: 'Select Version',
    time_title: 'Select Purchase Duration',
    month: 'Month',
    year: 'Year',
    credit_month_amount: 'Monthly {amount} credits',
    agent_bots_title: 'Available Agents',
    ai_assistant_title: 'Cross-platform AI Assistant',
    time_unit_month: 'One Month',
    time_unit_year: 'One Year',
    aside_title: 'New Order Purchase Details',
    aside_desc: 'Purchase for the following users',
    payment: 'Payment Method',
    wechat_pay: 'WeChat Payment',
    alipay: 'Alipay',
    manual_pay: 'Manual Transfer',
    paypal: 'PayPal',
    total: 'Total',
    order_title: 'Order Payment',
    pay_amount: 'Payment Amount',
    pay_by_wechat: 'Use WeChat QR Code to Pay',
    pay_policy: 'Payment is deemed to agree to the relevant {policy}',
    pay_success: 'Payment Successful',
    pay_confirm: 'Confirm payment completion, please click',
    payed: 'Paid',
    manual_pay_success_title: 'Order Generated',
    manual_pay_success_desc:
      'Please wait or contact the administrator to confirm the payment information',
    expire_time: 'Expire Time'
  },
  authority: {
    group_not_permission: 'You do not have permission to access this group',
    payment_not_setting:
      'The site has not configured payment methods, please contact the administrator directly',
    agent_not_permission:
      'You do not have permission to use this agent, please contact the administrator directly',
    login_not_permission: 'Please login first',
    use_range: 'Use Range'
  },
  upgrade_dialog: {
    title:
      'The number of registered users of the site has reached the upper limit, please contact the administrator~~',
    cancel: 'Close Registration'
  },
  order: {
    id: 'Order ID',
    subscription: 'Subscription Service',
    amount: 'Order Amount',
    pay_type: 'Payment Method',
    create_time: 'Order Time',
    status: 'Status',
    action: 'Action',
    search_placeholder: 'Please enter order ID',

    payment: 'Payment',
    cancel: 'Cancel',
    cancel_confirm: 'Are you sure you want to cancel this order?',

    status_list: {
      all: 'All',
      not_confirm: 'Not Confirm',
      pending: 'Pending',
      paid: 'Paid',
      expired: 'Expired',
      cancel: 'Canceled'
    }
  },
  filter: {
    start_time: 'Start Time',
    end_time: 'End Time',

    date_range: {
      today: 'Today',
      last_7_days: 'Last 7 Days',
      last_4_weeks: 'Last 4 Weeks',
      last_3_months: 'Last 3 Months',
      last_12_months: 'Last 12 Months',
      this_month: 'This Month',
      this_quarter: 'This Quarter',
      this_year: 'This Year',
      all_time: 'All Time'
    }
  },
  table: {
    footer_text: 'Total {total} items'
  },
  guide: {
    title: 'Welcome to 53AI Hub',
    description:
      'This is the initialization process. Please enter basic information (e.g., site details) to set up the system configuration.',
    website_info: 'Site Information',
    website_setting: 'Account Settings',
    website_success: 'Installation Completed',
    website_info_name: 'Site Name',
    website_info_name_placeholder: 'Please enter the site name',
    website_info_logo: 'Site Logo',
    website_info_logo_placeholder: 'Please upload the logo',
    website_info_logo_change: 'Change',
    website_info_logo_upload: 'Upload',
    website_info_logo_tip:
      'Please upload a square logo with 1:1 aspect ratio (recommended size: 512×512px). Supported formats: PNG/JPG. File size must not exceed 2MB.',
    website_style: 'Site Style',
    website_info_language: 'Default Language',
    website: 'Website Style',
    software: 'Software Style',
    init_success: 'Initialization Successful!',
    jump_now: 'Jump Immediately',
    jump_tip: 'Will automatically jump to the homepage in {count} seconds...',
    next: 'Next Step',
    init: 'Initialize',
    confirm_password: 'Confirm Password',
    confirm_password_placeholder: 'Please confirm your password again'
  }
}
